export interface Client {
  id?: number;
  organizationId?: string | null;
  razaoSocial?: string | null;
  fantasia?: string | null;
  endereco?: string | null;
  numero?: string | null;
  bairro?: string | null;
  cidade?: string | null;
  uf?: string | null;
  cep?: string | null;
  complemento?: string | null;
  moradia?: number | null;
  tipo?: number | null;
  situacao?: number | null;
  telefone1?: string | null;
  telefone2?: string | null;
  telefone3?: string | null;
  celular?: string | null;
  email?: string | null;
  rg?: string | null;
  cpf?: string | null;
  estadoCivil?: string | null;
  empresa?: string | null;
  dataCadastro?: Date | null;
  dataUltimaCompra?: Date | null;
  previsao?: Date | null;
  cnae?: string | null;
  codMunicipioIbge?: string | null;
  ibge?: string | null;
  correspEndereco?: string | null;
  correspBairro?: string | null;
  correspCidade?: string | null;
  correspUf?: string | null;
  correspCep?: string | null;
  correspComplemento?: string | null;
  correspNumero?: string | null;
  foto?: string | null;
  tipoCadastro?: string | null;
  ie?: string | null;
  mdia?: string | null;
  tDocumento?: string | null;
  tVencimento?: string | null;
  tCobranca?: string | null;
  retencoes?: string | null;
  simples?: string | null;
  correios?: string | null;
  email1?: string | null;
  email2?: string | null;
  email3?: string | null;
  email4?: string | null;
  email5?: string | null;
  contribuinte?: string | null;
  vlrMens?: number | null;
  observacao?: string | null;
  usaFor?: boolean | null;
  crt?: string | null;
  melhorDia?: string | null;
  vendedor?: string | null;
  teste?: string | null;
  travado?: boolean | null;
  ativo?: boolean | null;
  inadimplente?: boolean | null;
  especial?: boolean | null;
  bloqueado?: boolean | null;
  pessoa?: string | null;
  documentosPdf?: string | null;
  codigoAnterior?: string | null;
  createdAt?: Date | null;
  updatedAt?: Date | null;
}

export interface SearchClientsResult {
  data: Client[];
  pagination: {
    page: number;
    limit: number;
    total: number;
    totalPages: number;
  };
}