import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from '@clerk/nextjs';
import { dark } from '@clerk/themes';
import { ptBR } from '@clerk/localizations'; // Importar ptBR aqui

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ClerkProvider
          localization={ptBR} // Usar ptBR para localização
          appearance={{ baseTheme: dark }}
          signInUrl={'/sign-in'}
          signUpUrl={'/sign-up'}
          signInFallbackRedirectUrl={'/dashboard'} // Redirecionar para dashboard
          signUpFallbackRedirectUrl={'/dashboard'} // Redirecionar para dashboard
          afterSignOutUrl={'/'}
        >
          {children}
        </ClerkProvider>
      </body>
    </html>
  );
}
