CREATE TABLE IF NOT EXISTS "clients" (
	"id" serial PRIMARY KEY NOT NULL,
	"organization_id" text NOT NULL,
	"razao_social" text,
	"fantasia" text,
	"endereco" text,
	"numero" text,
	"bairro" text,
	"cidade" text,
	"uf" text,
	"cep" text,
	"complemento" text,
	"moradia" integer,
	"tipo" integer,
	"situacao" integer,
	"telefone1" text,
	"telefone2" text,
	"telefone3" text,
	"celular" text,
	"email" text,
	"rg" text,
	"cpf" text,
	"estado_civil" text,
	"empresa" text,
	"data_cadastro" timestamp,
	"data_ultima_compra" timestamp,
	"previsao" timestamp,
	"cnae" text,
	"cod_municipio_ibge" text,
	"ibge" text,
	"corresp_endereco" text,
	"corresp_bairro" text,
	"corresp_cidade" text,
	"corresp_uf" text,
	"corresp_cep" text,
	"corresp_complemento" text,
	"foto" text,
	"tipo_cadastro" text,
	"ie" text,
	"mdia" text,
	"t_documento" text,
	"t_vencimento" text,
	"t_cobranca" text,
	"retencoes" text,
	"simples" text,
	"correios" text,
	"email1" text,
	"email2" text,
	"email3" text,
	"email4" text,
	"email5" text,
	"contribuinte" text,
	"vlr_mens" numeric(15, 2),
	"observacao" text,
	"usa_for" integer,
	"crt" text,
	"melhor_dia" text,
	"vendedor" text,
	"travado" boolean DEFAULT false,
	"ativo" boolean DEFAULT false,
	"inadimplente" boolean DEFAULT false,
	"especial" boolean DEFAULT false,
	"bloqueado" boolean DEFAULT false,
	"pessoa" text DEFAULT 'J',
	"documentos_pdf" text,
	"codigo_anterior" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "clients" ADD CONSTRAINT "clients_organization_id_organization_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organization"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
